services:
  # Database container: PostgreSQL
  movies-db:
    image: postgres:latest
    container_name: movies-db.howestprime.dev
    env_file:
      - .env
    ports:
      - "40021:5000"
    volumes:
      - movies_db_data:/var/lib/postgresql/data
    networks:
      - movies-dev-network

  # Messagebroker container: LavinMQ
  messagebroker:
    image: cloudamqp/lavinmq:latest
    container_name: messagebroker.howestprime.dev
    ports:
      - "40000:5672"   # AMQP port
      - "40001:15672"  # Management GUI
    networks:
      - movies-dev-network

networks:
  movies-dev-network:
    name: movies-howestprime-dev
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16

volumes:
  movies_db_data: