name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Execute Tests
      run: dotnet test test/UnitTests/UnitTests.csproj --no-restore --configuration Release --verbosity normal

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: [unit-tests]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate Coverage Report
      run: |
        dotnet test test/UnitTests/UnitTests.csproj --configuration Release \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=opencover \
        /p:Threshold=97 \
        /p:ThresholdType=line \
        /p:Include=\"[Howestprime.Movies.Application]*,[Howestprime.Movies.Domain]*\"

    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: "**/coverage.opencover.xml"

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [coverage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL_PASSWORD }} | docker login ${{ vars.AZ_CONTAINER_REGISTRY }} -u ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL }} --password-stdin

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish .NET app
        run: dotnet publish -c Release -p:PublishProfile=production -p:ContainerRegistry=${{ vars.AZ_CONTAINER_REGISTRY }} -p:ContainerImageTag=1.0.0 /t:PublishContainer

  deploy:
    name: Deploy to Azure Container Apps
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL }} -p ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL_PASSWORD }} --tenant ${{ vars.AZ_TENANT_ID }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp create \
          --name microservice-movies \
          --resource-group ${{ vars.AZ_RESOURCE_GROUP }} \
          --environment ${{ vars.AZ_CONTAINER_ENVIRONMENT }} \
          --image ${{ vars.AZ_CONTAINER_REGISTRY }}/microservice-movies:1.0.0 \
          --registry-server ${{ vars.AZ_CONTAINER_REGISTRY }} \
          --registry-username ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL }} \
          --registry-password ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL_PASSWORD }} \
          --user-assigned "${{ vars.HOWESTPRIME_WIDE_MI_KEYVAULTREADER_URI}}" \
          \
          --secrets \
          "db-password=keyvaultref:${{vars.HOWESTPRIME_MOVIES_P_SQLSRV_PASSWORD_URI}},identityref:${{vars.HOWESTPRIME_WIDE_MI_KEYVAULTREADER_URI}}" \
          "mb-password=keyvaultref:${{vars.HOWESTPRIME_WIDE_P_MESSAGEBROKER_PASSWORD_URI}},identityref:${{vars.HOWESTPRIME_WIDE_MI_KEYVAULTREADER_URI}}" \
          \
          --env-vars \
          ASPNETCORE_ENVIRONMENT=Production \
          "Database__Password=secretref:db-password" \
          "Database__Username=${{vars.HOWESTPRIME_MOVIES_P_PSQL_LOGIN}}" \
          "Database__ConnectionString=${{vars.HOWESTPRIME_MOVIES_P_PSQL_CONNECTION_STRING}}" \
          "MessageBroker__Hostname=${{vars.HOWESTPRIME_WIDE_P_MESSAGEBROKER_HOSTNAME}}" \
          "MessageBroker__VirtualHost=${{vars.HOWESTPRIME_WIDE_P_MESSAGEBROKER_VHOST}}" \
          "MessageBroker__Password=secretref:mb-password" \
          "MessageBroker__Username=${{vars.HOWESTPRIME_WIDE_P_MESSAGEBROKER_LOGIN}}" 
          
          az containerapp ingress enable \
          --name microservice-movies \
          --resource-group ${{ vars.AZ_RESOURCE_GROUP }} \
          --type external \
          --target-port 8000